parameters:
- name: awsEnvName
  default: ''
- name: msHostedPoolVmImage
  default: ''
- name: privatePoolName
  default: ''
- name: artifactName
  default: ''
- name: archiveFilePathToExtract
  default: ''
- name: azureDevOpsVarGroups
  type: object
  default: []
- name: azureDevOpsSecureFiles
  type: object
  default: []
- name: azurermBackendStorageContainer
  default: ''
- name: azurermBackendStorageContainerBlobKey
  default: ''
- name: deployInfraTFLayerFolder
  default: ''
- name: pipelineResourceIdentifier
  default: ''
- name: inputTFVarDefinitionFiles
  type: object
  default: []
- name: inputTFVars
  type: object
  default: []
- name: tfLog
  type: string
  default: 'UNSET'
  values:
  - UNSET
  - TRACE
  - DEBUG
  - INFO
  - WARN 
  - ERROR

stages:
- stage: 'Terraform_Plan_Destroy_${{ parameters.awsEnvName }}'
  dependsOn: []
  condition: in(variables['Build.Reason'], 'Manual')
  displayName: 'Terraform Plan Destroy ${{ parameters.awsEnvName }}'
  ${{ if ne(length(parameters.azureDevOpsVarGroups), 0) }}:
    variables:
    - ${{ each variableGroup in parameters.azureDevOpsVarGroups }}:
      - group: ${{variableGroup}}
  jobs:
  - job: Terraform_Plan_Destory
    displayName: Terraform Plan Destroy ${{ parameters.awsEnvName }}
    pool:
      ${{ if ne(parameters.msHostedPoolVmImage, '') }}:
        vmImage: ${{ parameters.msHostedPoolVmImage }}
      ${{ if ne(parameters.privatePoolName, '') }}:
        name: ${{ parameters.privatePoolName }}
    container:
      image: acr5064.azurecr.io/tf-container-aws-ubuntu1904:latest
      endpoint: CIO-5064-Tfmod-Pull-ACR
    workspace:
      clean: all
    steps:
    - ${{ each secureFile in parameters.azureDevOpsSecureFiles }}:
      - task: DownloadSecureFile@1
        displayName: 'Download secure file ${{secureFile}}'
        inputs:
          secureFile: ${{secureFile}}
        enabled: true
    
    - download: ${{ parameters.pipelineResourceIdentifier }}
      enabled: true

    - task: ExtractFiles@1
      displayName: 'Extract Artifact'
      inputs:
        archiveFilePatterns: '$(Pipeline.Workspace)/${{ parameters.pipelineResourceIdentifier }}/${{ parameters.artifactName }}/${{ parameters.archiveFilePathToExtract }}'
        destinationFolder: '$(Pipeline.Workspace)/build-bundle-${{ parameters.artifactName }}-extract'
        cleanDestinationFolder: true
      enabled: true

    - task: CIODevOps.azuredevOps-build-agent-cf-cli-config-file-generator.custom-build-release-task.AzureDevOps Build Agent TF Cli Config File Generator@0
      displayName: 'AzureDevOps Build Agent TF Cli Config File Generator'
      enabled: true

    - task: Powershell@2
      displayName: Prepare for Terraform Registries
      continueOnError: false
      timeoutInMinutes: 2  
      inputs:
        targetType: inline
        script: |
          Write-Host "[Debug]Agent OS is: $env:AGENT_OS"
          # For Windows Build Agentww
          if ($env:AGENT_OS -match '^.*Windows.*$') {
              Write-Host "[Debug]...........Windows Agent Detected........"
              if (Test-Path "$($env:APPDATA)/terraform.rc") {
                $oriTfRcFilePath = "$($env:APPDATA)/terraform.rc"
                $oriTfRcStr = Get-Content "$oriTfRcFilePath" -Raw
                $oriTfRcStr = $oriTfRcStr -replace "acnciotfregistry.accenture.com", "acnciotfregistry.ciostage.accenture.com"
                Add-Content $oriTfRcFilePath "`n $oriTfRcStr"
              }
          # For Linux Build Agent
          } ElseIf ($env:AGENT_OS -match '^.*Linux.*$') {
              Write-Host "[Debug]...........Linux Agent Detected........"
              if (Test-Path "~/.terraformrc") {
                $oriTfRcFilePath = "~/.terraformrc"
                $oriTfRcStr = Get-Content "$oriTfRcFilePath" -Raw
                $oriTfRcStr = $oriTfRcStr -replace "acnciotfregistry.accenture.com", "acnciotfregistry.ciostage.accenture.com"
                Add-Content $oriTfRcFilePath "`n $oriTfRcStr"
              }
          } else {
              Write-Error "[Error]*********Agent OS is neither Windows nor Linux: $env:AGENT_OS **********"
          }
      enabled: true 
  
    - task: Powershell@2
      displayName: Authenticate Azure CLI and PowerShell
      continueOnError: false
      timeoutInMinutes: 2  
      inputs:
        targetType: inline
        script: |
          & "/sharedfolder/test/Set-AuthenticationContext.ps1" -usesCertificate $true
          Get-ChildItem -Path ./ -Recurse

          Write-Host "[Debug] Param azurermBackendStorageContainer is ${{ parameters.azurermBackendStorageContainer }}"

          $container_name = "cio-proj$(PROJECT_AIR_ID)$(ENVIRONMENT)tfstate"
          
          $blob = "${{ parameters.azurermBackendStorageContainerBlobKey }}env:${{ parameters.awsEnvName }}"
          Write-Host "[Debug] Checking Container $container_name for blob_key $blob"

          $blob_detail = az storage blob exists --auth-mode login --container-name $container_name --account-name st506405use2tfstate --subscription sb-506405 --name $blob | ConvertFrom-Json
          Write-Host "[Debug] blob_detail is $blob_detail"

          if((-not [string]::IsNullOrEmpty("${{ parameters.azurermBackendStorageContainer }}")) -and $container_name -ne "${{ parameters.azurermBackendStorageContainer }}")
          {
            Write-Host "[Debug] blob container are not identical"
            # whether old blob exists or not
            $old_blob = $null
            $old_blob_detail = az storage blob exists --account-key $env:ARM_ACCESS_KEY --account-name sa5064iactf --auth-mode key --container-name "${{ parameters.azurermBackendStorageContainer }}" --name $blob | ConvertFrom-Json
            Write-Host "[Debug] old_blob_detail is $old_blob_detail"
            # if exists, then download
            if ($($old_blob_detail.exists)) {
              Write-Host "[Debug] Old Blob exists"
              $old_blob = az storage blob download --account-key $env:ARM_ACCESS_KEY --account-name sa5064iactf --auth-mode key --container-name "${{ parameters.azurermBackendStorageContainer }}" --file ./terraform.tfstate --name $blob | ConvertFrom-Json
              Write-Host "[Debug] Old Blob is $old_blob"
            }
          }
          
          if($null -ne $old_blob -and $null -ne $old_blob.name)
          {
            Write-Host "[Debug] Blob Detail: $blob_detail"
            Write-Host "[Debug] Blob $blob Exists in Remote Backend: $($blob_detail.exists)"
            Write-Output ("##vso[task.setvariable variable=BLOB_EXISTS]$($blob_detail.exists)")
            Write-Output ("##vso[task.setvariable variable=blob]$blob")
            Write-Output ("##vso[task.setvariable variable=container_name]$container_name")
          }
      env:
        ARM_ACCESS_KEY: $(TOOL_TF_BACKEND_KEY)
        ARM_CLIENT_CERTIFICATE_PATH: $(Agent.TempDirectory)/$(AZURE_PFX_CERT_NAME)
        ARM_CLIENT_CERTIFICATE_PASSWORD: $(ARM_CLIENT_CERTIFICATE_PASSWORD)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: "3de4faec-c7e9-4255-95af-ab63b5e7c44a"
      enabled: false 

    - task: Powershell@2
      displayName: Migrate to Cloud 2.0 Remote Backend Storage Account
      name: migrate_to_new_storage
      condition: and(succeeded(), eq(variables['BLOB_EXISTS'], false))        
      inputs:
        targetType: inline
        script: |
          az storage blob upload --account-name st506405use2tfstate --auth-mode login --file ./terraform.tfstate --container-name $(container_name)  --subscription sb-506405 --name $(blob) --content-type "application/json"
        failOnStderr: false
      enabled: false

    - task: Powershell@2
      displayName: Terraform Init
      name: tf_init
      continueOnError: false
      timeoutInMinutes: 2
      inputs:
        targetType: inline
        script: |
          Get-ChildItem

          $cmdArgs = @(
              "init"
              "-no-color"
              "-backend-config=`"subscription_id=3de4faec-c7e9-4255-95af-ab63b5e7c44a`""
              "-backend-config=`"resource_group_name=rg-506405sharedservices`""
              "-backend-config=`"storage_account_name=st506405use2tfstate`""
              "-backend-config=`"container_name=cio-proj$(PROJECT_AIR_ID)$(ENVIRONMENT)tfstate`""
              "-backend-config=`"key=${{ parameters.azurermBackendStorageContainerBlobKey }}`""
              "./"
            )
          Write-Host  $cmdArgs 
          terraform $cmdArgs
        failOnStderr: true # Optional
        workingDirectory: $(Pipeline.Workspace)/build-bundle-${{ parameters.artifactName }}-extract/${{ parameters.deployInfraTFLayerFolder}}
      env:
        AWS_SECRET_ACCESS_KEY: $(NEW_AWS_SECRET_KEY)
        AWS_ACCESS_KEY_ID: $(NEW_AWS_ACCESS_KEY)
        AWS_REGION: $(AWS_REGION)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(DATABRICKS_AZURE_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
      enabled: true

    - bash: |
        terraform workspace select ${{ parameters.awsEnvName }} || terraform workspace new ${{ parameters.awsEnvName }} 
        terraform workspace list -no-color 
      displayName: 'Terraform Use Workspace'
      workingDirectory: $(Pipeline.Workspace)/build-bundle-${{ parameters.artifactName }}-extract/${{ parameters.deployInfraTFLayerFolder}}
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(DATABRICKS_AZURE_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: "3de4faec-c7e9-4255-95af-ab63b5e7c44a"
      enabled: true

    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in tfvars for specific environment'
      inputs:
        rootDirectory: $(Pipeline.Workspace)/build-bundle-${{ parameters.artifactName }}-extract/${{ parameters.deployInfraTFLayerFolder}}
        targetFiles: |
         **/*.tfvars
      enabled: true

    - task: Powershell@2
      displayName: Terraform Plan Destroy
      name: tf_plan_destroy_in_wks
      continueOnError: false
      timeoutInMinutes: 60
      inputs:
        targetType: inline
        script: |
          Write-Host "[Debug] Get Items in current location"
          Get-ChildItem

          ################## 1. Update TF_LOG mode ##################
          Write-Host "[Info] 1. Start to copy secure files"
          if ("${{ parameters.tfLog }}" -ne "UNSET"){
              $Env:TF_LOG="${{ parameters.tfLog }}"
              Write-Host "[Info] TF_LOG is set to $($Env:TF_LOG)"
              Get-ChildItem env:
          } else {
              Write-Host "[Info] TF_LOG is unset"
          }

          ################## 2. Copy secure files if exists ##################
          $azureDevOpsSecureFiles = "${{ join(';', parameters.azureDevOpsSecureFiles) }}"
          Write-Host "[Info] 2. Start to copy secure files"
          if (![string]::IsNullOrEmpty($azureDevOpsSecureFiles)) {
              Get-ChildItem $(Agent.TempDirectory)
              $azureDevOpsSecureFiles.Split(";") | ForEach {
                if (![string]::IsNullOrEmpty($_)) {
                  if (Test-Path "$(Agent.TempDirectory)/$_"){
                      Copy-Item $(Agent.TempDirectory)/$_ .
                  } else {
                      Write-Host "[Error] Secure file not exists in Agent.TempDirectory"
                  }
                } else {
                    Write-Host "[Error] single inputTFVarDefinitionFile is empty"
                }
              }
          } else {
              Write-Host "[Info] azureDevOpsSecureFiles is empty"
          }

          Write-Host "[Debug] Get Items in current location"
          Get-ChildItem

          ################## 3. Terraform init ##################
          Write-Host "[Info] 3. Start to rerun terraform init"
          $cmdArgs = @(
              "init"
              "-no-color"
              "-backend-config=`"subscription_id=3de4faec-c7e9-4255-95af-ab63b5e7c44a`""
              "-backend-config=`"resource_group_name=rg-506405sharedservices`""
              "-backend-config=`"storage_account_name=st506405use2tfstate`""
              "-backend-config=`"container_name=cio-proj$(PROJECT_AIR_ID)$(ENVIRONMENT)tfstate`""
              "-backend-config=`"key=${{ parameters.azurermBackendStorageContainerBlobKey }}`""
              "./"
            )
          Write-Host  $cmdArgs 
          terraform $cmdArgs
          
          $cmdArgs = @(
              "plan"
              "-destroy"
              "-input=false"
              "-out"
              "`"tfplan.bin`""
              "-no-color"
          )
          
          ################## 4. Terraform Plan ##################
          Write-Host "[Info] 4. Start to run terraform plan"
          # Handle terraform variable definitions (.tfvars) files
          $inputTFVarDefinitionFiles = "${{ join(';', parameters.inputTFVarDefinitionFiles) }}"
          Write-Host "[Info] inputTFVarDefinitionFiles is $inputTFVarDefinitionFiles"
          if (![string]::IsNullOrEmpty($inputTFVarDefinitionFiles)) {
              $inputTFVarDefinitionFiles.Split(";") | ForEach {
                if (![string]::IsNullOrEmpty($_)) {
                  $cmdArgs += -join('-var-file=', '"', $_, '"')
                }
              }
          } else {
            Write-Host "[Info] inputTFVarDefinitionFiles is empty"
          }

          # Handle variables on the Command Line
          $inputTFVars = "${{ join(';', parameters.inputTFVars) }}"
          Write-Host "[Info] inputTFVars is $inputTFVars"
          if (![string]::IsNullOrEmpty($inputTFVars)) {
              $inputTFVars.Split(";") | ForEach {
                if (![string]::IsNullOrEmpty($_)) {
                  $cmdArgs += -join('-var=', '"', $_, '"')
                }
              }
          } else {
            Write-Host "[Info] inputTFVars is empty"
          }

          $Env:TF_VAR_assume_role_arn = $Env:NEW_APP_TEAM_DEPLOYER_ROLE
          $Env:TF_VAR_access_key  = $Env:NEW_AWS_ACCESS_KEY
          $Env:TF_VAR_secret_key  = $Env:NEW_AWS_SECRET_KEY
          $Env:TF_VAR_region  = $Env:AWS_REGION
          
          Write-Host "[Debug] cmdArgs is $cmdArgs"

          terraform $cmdArgs
        failOnStderr: true
        workingDirectory: $(Pipeline.Workspace)/build-bundle-${{ parameters.artifactName }}-extract/${{ parameters.deployInfraTFLayerFolder}}
      env:
        NEW_AWS_SECRET_KEY: $(NEW_AWS_SECRET_KEY)
        NEW_AWS_ACCESS_KEY: $(NEW_AWS_ACCESS_KEY)
        AWS_REGION: $(AWS_REGION)
        NEW_APP_TEAM_DEPLOYER_ROLE: $(NEW_APP_TEAM_DEPLOYER_ROLE)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID) 
        ARM_CLIENT_SECRET: $(DATABRICKS_AZURE_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: "3de4faec-c7e9-4255-95af-ab63b5e7c44a"
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        GOOGLE_OAUTH_ACCESS_TOKEN: "none"
      enabled: true